# Generated by Django 2.2.14 on 2021-04-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
